FROM ubuntu:xenial

#Default branch name
ARG BRANCH_NAME=UI
#Default
ARG REPO_SLUG=PXN-Foundation/Peepcoin
ENV REPO_SLUG=${REPO_SLUG}
ENV REPO_URL=https://github.com/${REPO_SLUG}

RUN apt-get -qq update && \
    apt-get -qqy install \
    git \
    sudo
#RUN git clone ${REPO_URL} --branch $BRANCH_NAME --single-branch --depth 1

COPY peepcoin.tar.gz /peepcoin.tar.gz
RUN tar -xvf /peepcoin.tar.gz

#xenial
#Missing requirement: libtool
RUN apt install -yqq libtool-bin
RUN cd /peepcoin/scripts/windows-crosscompile && ./dependencies.sh
RUN cd /peepcoin && scripts/windows-crosscompile/compile-peepcoin.sh
